window.PRODUCTS_DATA = {
  "cat-valves": { "theme": "light", "products": [
    {"code":"HVS","name":"Electric Control Globe Valve","desc":"Linear electric actuator with multi-stage precision gearbox. ±1% positioning accuracy. For steam, hot water and chemical pipelines.","image":"https://chinaheimayi.com/wp-content/uploads/2026/04/HVS-Electric-Control-Valve-Globe-Valve.png","tags":["DN15–DN150","PN16/PN25","−20°C to 280°C","4-20mA / RS485 / Modbus"]},
    {"code":"HVB","name":"Electric Butterfly & Ball Valve","desc":"Quarter-turn electric actuator. Butterfly (DN50–DN500) and ball (DN15–DN300) options. Dual mechanical + electronic limit protection.","image":"https://chinaheimayi.com/wp-content/uploads/2026/02/Butterfly-Valve-1.webp","tags":["DN15–DN500","PN16/PN25","±1% accuracy","4-20mA / RS485 / M-Bus"]},
    {"code":"HVA","name":"Electric Three-way Valve","desc":"T-type (mixing) and L-type (diverting) configurations. ±1% mixing ratio accuracy. Full-stroke response ≤5 seconds. For chiller blending and process switching.","image":"images/hva-electric-threeway-valve.jpg","tags":["DN15–DN300","PN16–PN64","4-20mA / RS485 / Modbus / HART"]},
    {"code":"HVM Wired","name":"Wired Miniature Ball Valve","desc":"Compact electric ball valve with RS485 / Modbus. 0–100% aperture at ±1% accuracy. For small-scale fluid control in smart homes and HVAC.","image":"https://chinaheimayi.com/wp-content/uploads/2026/06/HVM-Wired-Transmission-Mini-Globe-Valve-1.webp","tags":["DN8–DN40","DC 12–24V","100,000 cycles","RS485 Modbus"]},
    {"code":"HVM Wireless","name":"Wireless Miniature Ball Valve","desc":"LoRaWAN / 4G, Li-ion battery powered. Zero-wiring smart valve. OTA firmware updates. 100,000-cycle rated. Deploy in minutes.","image":"https://chinaheimayi.com/wp-content/uploads/2026/06/HVM-Wireless-Transmission-Mini-Globe-Valve-1.webp","tags":["DN8–DN40","LoRaWAN / 4G","Battery powered","OTA updates"]},
    {"code":"HVI","name":"Solar Irrigation Valve","desc":"Solar-powered smart valve for agriculture and landscaping. 10–20W mono panel. 7–15 days backup battery. LoRaWAN / 4G up to 10km range.","image":"images/hvi-solar-irrigation-valve.jpg","tags":["UPVC / PP-GF body","IP67","LoRaWAN / 4G","Soil sensor compatible"]}
  ]},
  "cat-instruments": { "theme": "dark", "products": [
    {"code":"HTT Mini","name":"Miniature Temperature Transmitter","desc":"High-precision compact temperature transmitter. Direct pipe mount. LoRaWAN / NB-IoT / 4G / RS485. ±0.1°C accuracy.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/HTT-Series-Hirschman-Miniature-Temperature-Transmitter.webp","tags":["−50°C to 200°C","±0.1°C","LoRaWAN / NB-IoT / 4G / RS485","IP65"]},
    {"code":"HTT","name":"Temperature Transmitter (2-wire)","desc":"Thermocouple and RTD transmitter. Installs directly in sensor junction box. 4-20mA output. HART / Modbus compatible.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/HTT-Series-Temperature-Transmitter.webp","tags":["−40°C to 150°C","±0.1–0.5°C","HART / Modbus","IP65 · Ex rated"]},
    {"code":"HPT Mini","name":"Miniature Pressure Transmitter","desc":"Ultra-compact pressure sensor. Direct pipeline mount from DN25. ±0.1% FS accuracy. IP67/IP68. Explosion-proof option.","image":"https://chinaheimayi.com/wp-content/uploads/2025/11/Miniature-pressure-transmitter-1.png","tags":["0–100 MPa range","±0.1% FS","4-20mA / RS485 / HART","IP67/IP68"]},
    {"code":"HPT","name":"Intelligent Pressure Transmitter","desc":"Smart pressure transmitter with IoT cloud connectivity. ±0.075% FS accuracy. HART 7.0 compatible. Remote calibration.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/HPT-series-Husman-Type-Pressure-Transmitter-1.webp","tags":["−0.1 to 60 MPa","±0.075% FS","4-20mA / HART / Modbus","IP65/IP67"]},
    {"code":"HPT ΔP","name":"Differential Pressure Transmitter","desc":"For flow calculation, liquid level and filter monitoring. ±0.075% accuracy. 100:1 turndown ratio. LoRaWAN wireless option.","image":"https://chinaheimayi.com/wp-content/uploads/2025/11/differential-pressure-transmitter-5.png","tags":["0–10 MPa","±0.075% FS","HART / Modbus / LoRaWAN","IP65/IP67"]},
    {"code":"HLP Flange","name":"Flange Level Transmitter","desc":"For high-viscosity, crystallizing or corrosive fluids. ±0.1% FS. 316L / Hastelloy / Tantalum diaphragm. IP68.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/HLP-Series-Flange-Level-Transmitter.webp","tags":["±0.1% FS","−40°C to 200°C","4-20mA / HART / Modbus","IP68"]},
    {"code":"HLP Immersion","name":"Immersion Level Gauge","desc":"Drop-in level sensor for tanks, rivers and deep wells. 0.3–110m range. ±0.1% FS. 4G wireless option. IP68.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/HLP-Series-Immersion-Level-Gauge.webp","tags":["0.3–110 m","±0.1% FS","4-20mA / RS485 / 4G","IP68"]},
    {"code":"HOR","name":"Radar Level Gauge","desc":"26 GHz / 80 GHz FMCW radar. ±1mm accuracy. 0–70m liquid, 0–35m solid. Non-contact — works on any media.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/HOR-Radar-Level_Liquid-Level-Gauge-1.webp","tags":["±1 mm accuracy","0–70 m range","4-20mA / HART / RS485","−40°C to 100°C"]}
  ]},
  "cat-flow": { "theme": "light", "products": [
    {"code":"HFE","name":"Electromagnetic Flowmeter","desc":"For conductive liquids including slurry. No pressure drop. Bi-directional. PTFE / rubber liner. DN10–DN3000.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/Intelligent-Electromagnetic-Flowmeter.webp","tags":["DN10–DN3000","±0.5% accuracy","4-20mA / RS485 / LoRaWAN","IP68"]},
    {"code":"HFU","name":"Ultrasonic Flowmeter","desc":"Clamp-on or inline ultrasonic. Zero installation downtime for clamp-on version. For clean liquids in any pipe material.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/ultrasonic-flow-meter.png","tags":["DN15–DN6000","±1% accuracy","4-20mA / RS485 / Modbus","Clamp-on available"]},
    {"code":"HFV","name":"Vortex Flowmeter","desc":"For steam, gas and liquid. No moving parts. Integrated temperature/pressure compensation. DN15–DN300.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/Intelligent-Vortex-Flowmeter.webp","tags":["DN15–DN300","±1% liquid / ±1.5% gas","4-20mA / RS485 / HART"]},
    {"code":"HFS","name":"Spiral Vortex Flowmeter","desc":"Spiral-type precession vortex for gas measurement. Very low pressure drop. DN25–DN200. Suitable for compressed air and natural gas.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/Spiral-Vortex-Flowmeter.webp","tags":["DN25–DN200","±1% accuracy","4-20mA / RS485 / HART"]},
    {"code":"HFT","name":"Turbine Flowmeter","desc":"High-precision turbine for clean liquids and gases. 0.2% accuracy for liquid. DN4–DN600. Pulse + 4-20mA output.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/Intelligent-Turbine-Flowmeter.webp","tags":["DN4–DN600","±0.2% liquid","Pulse / 4-20mA / RS485"]},
    {"code":"HFTA","name":"Target Flowmeter","desc":"For high-viscosity, slurry and fibrous media. No moving parts. For paper pulp, heavy oil, molten materials. DN15–DN200.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/Target-Flowmeter.webp","tags":["DN15–DN200","High-viscosity media","4-20mA / RS485 / HART"]},
    {"code":"HFR","name":"Gas Roots Flowmeter","desc":"Positive displacement roots meter for gas. ±1% accuracy. For natural gas, LPG and industrial gases. DN25–DN200.","image":"https://chinaheimayi.com/wp-content/uploads/2026/01/Intelligent-Gas-Roots-Flowmeter.png","tags":["DN25–DN200","±1% accuracy","Pulse / 4-20mA / RS485"]},
    {"code":"HFG","name":"Gas Turbine Flowmeter","desc":"High-precision turbine for natural gas and industrial gas metering. Temperature and pressure compensation. DN15–DN300.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/Intelligent-Gas-Turbine-Flow-meter.webp","tags":["DN15–DN300","±1% accuracy","Pulse / 4-20mA / HART"]},
    {"code":"HFM","name":"Thermal Gas Mass Flowmeter","desc":"Thermal dispersion for compressed air, nitrogen and mixed gas. Measures mass flow directly — no temperature/pressure correction needed.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/Thermal-Gas-Mass-Flowmeter.webp","tags":["Compressed air / N₂","±2% of reading","4-20mA / RS485 / Modbus"]},
    {"code":"HFO","name":"Orifice Plate Flowmeter","desc":"Classic differential pressure orifice for steam, gas and liquid. Standard square-edged or conditioning orifice. ASME B16.36 flanged.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/Orice-Plate-Flowmeter.webp","tags":["Gas / Steam / Liquid","±0.5–1% accuracy","4-20mA / HART"]}
  ]},
  "cat-water": { "theme": "dark", "products": [
    {"code":"HWM Magnetic","name":"IoT Magnetic Water Meter","desc":"Standard IoT magnetic impeller meter. LoRaWAN / NB-IoT / M-Bus. Tamper-proof magnetic sensing. For residential district metering.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/W326-Series-IoT-Magnetic-Water-Meter.webp","tags":["DN15–DN40","Class B/C","LoRaWAN / NB-IoT / M-Bus","IP68"]},
    {"code":"HWM Non-magnetic","name":"IoT Non-magnetic Water Meter","desc":"Proprietary non-contact electronic sensing — immune to magnetic interference attacks. For high-security metering environments.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/W356-Series-IoT-Non-magnetic-Water-Meter.webp","tags":["DN15–DN40","Anti-tamper","LoRaWAN / NB-IoT","IP68"]},
    {"code":"HWM IC Card","name":"IC Card Prepaid Smart Water Meter","desc":"Prepaid card-based water meter with remote top-up and valve control. Automatic shutoff on credit depletion. For residential billing.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/LXSZ-F-Series-IC-Card-Intelligent-Magnetic-Water-Meter.webp","tags":["DN15–DN25","Prepaid / Postpaid","Remote valve control","IP68"]},
    {"code":"HWM Photo","name":"Photoelectric Remote Water Meter","desc":"Photoelectric absolute encoder reading — no mechanical drift. Ultra-low power. LoRaWAN / NB-IoT. Compatible with existing meter dials.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/LXSY-series-electronic-remote-water-meter-photoelectricon.webp","tags":["DN15–DN40","Absolute encoder","LoRaWAN / NB-IoT","10-yr battery"]},
    {"code":"HWM Valve","name":"IoT Valve-Controlled Water Meter","desc":"Metering + remote valve control in one unit. For district water management, leakage control and smart shut-off.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/Small-Diameter-Water-Meter-1.webp","tags":["DN15–DN50","Remote on/off","LoRaWAN / NB-IoT / 4G","IP68"]},
    {"code":"HWM Vertical","name":"Large-diameter IoT Vertical Spiral Wing Meter","desc":"Vertical-installation large-diameter spiral wing water meter for apartment blocks and commercial buildings.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/WS-Series-Large-diameter-IoT-Vertical-Spiral-Wing-Water-Meter.webp","tags":["DN50–DN200","Class C","LoRaWAN / NB-IoT / M-Bus","IP68"]},
    {"code":"HWM Horizontal","name":"Large-diameter IoT Horizontal Spiral Wing Meter","desc":"Horizontal multi-jet spiral wing meter for commercial buildings and industry. Wide diameter range for main supply lines.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/WS-Series-Large-diameter-IoT-Horizontal-Spiral-Wing-Water-Meter.webp","tags":["DN40–DN300","Class C","LoRaWAN / NB-IoT / M-Bus","IP68"]},
    {"code":"HWU Small","name":"Small-diameter Ultrasonic IoT Meter","desc":"Transit-time ultrasonic meter for residential and light commercial pipelines. No moving parts, temperature-compensated measurement.","image":"","tags":["DN15–DN40","Class 2","LoRaWAN / NB-IoT / M-Bus / RS485","IP68"]},
    {"code":"HWU","name":"Large-diameter Ultrasonic IoT Meter","desc":"Ultrasonic large-diameter water meter for main supply lines. No moving parts. Class 2. DN50–DN300. Long-term stable accuracy.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/LXC-Series-Large-diameter-Ultrasonic-IoT-Water-Meter.webp","tags":["DN50–DN300","Class 2","M-Bus / RS485 / 4G / NB-IoT","IP68"]},
    {"code":"HWC Direct","name":"IoT Camera Direct-reading Module","desc":"Camera-based AI module for direct dial reading on any legacy mechanical meter. Retrofit existing meters to IoT with zero replacement.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/WP101-IoT-Camera-Direct-Reading-Module.webp","tags":["Retrofit any meter","AI digit recognition","LoRaWAN / NB-IoT / 4G","IP65"]},
    {"code":"HGCA","name":"IoT Camera Gateway","desc":"Concentrator gateway for camera-reading systems. Manages multiple HWC modules. 4G backhaul to cloud. Wall or pole mount.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/WP102-IoT-Camera-Remote-Transmission-Module.webp","tags":["Multi-node gateway","4G uplink","Cloud-ready","IP65"]}
  ]},
  "cat-data": { "theme": "light", "products": [
    {"code":"HGI","name":"IoT Data Collection Terminal","desc":"Multi-protocol concentrator collecting from M-Bus, RS485, LoRaWAN devices. Uploads to cloud via NB-IoT / 4G / Ethernet. DIN-rail mount.","image":"https://chinaheimayi.com/wp-content/uploads/2026/02/IoT-Data-Collection-Terminal-1.webp","tags":["M-Bus / RS485 / LoRaWAN input","NB-IoT / 4G / Ethernet uplink","DIN-rail"]},
    {"code":"HGI Edge","name":"Edge Data Collection Computer","desc":"Industrial edge computer with local data processing and storage. Supports SCADA integration, local logic control and cloud upload. Fanless, IP65.","image":"https://chinaheimayi.com/wp-content/uploads/2026/02/Edge-Data-Acquisition-Computer-2.webp","tags":["Local processing","SCADA / Modbus / BACnet","4G / Ethernet","IP65"]},
    {"code":"HGC","name":"Centralized Supermeter","desc":"M-Bus concentrator that reads all connected smart meters and uploads batched data to management platform via 4G / NB-IoT.","image":"https://chinaheimayi.com/wp-content/uploads/2026/01/G101-Data-Collector-1.webp","tags":["M-Bus master","Up to 250 slave meters","4G / NB-IoT uplink","DIN-rail"]},
    {"code":"PLC","name":"Intelligent Logic Controller","desc":"Industrial PLC for automated pump station, valve and equipment control. Modbus RTU/TCP, supports local HMI and cloud SCADA integration.","image":"https://chinaheimayi.com/wp-content/uploads/2026/02/Edge-Data-Acquisition-Computer-1.webp","tags":["Modbus RTU / TCP","Digital & Analog I/O","Cloud SCADA","DIN-rail"]}
  ]},
  "cat-city": { "theme": "dark", "products": [
    {"code":"HMC","name":"Intelligent Manhole Cover Monitor","desc":"Tilt, displacement and vibration sensors. Real-time tamper alerts. GPS/BeiDou positioning. Flood level detection. 6-year battery. IP67.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/H501-Intelligent-Manhole-Cover-Monitoring-Instrument.webp","tags":["GPS / BeiDou","4G / LoRa","6-yr battery","IP67","Methane sensor option"]},
    {"code":"HEM","name":"Environmental Monitoring Station","desc":"Multi-parameter meteorological station. PM2.5/PM10, noise, temperature, humidity, wind speed/direction, CO/SO₂/NO₂/O₃, soil sensors. Solar powered.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/Environmental-Monitoring-Station.webp","tags":["30+ sensor types","NB-IoT / 4G","Solar powered","LED display option"]},
    {"code":"HLL","name":"Smart Logistics Locator","desc":"IoT asset tracker for cold chain, high-value cargo and returnable packaging. BeiDou / LBS positioning, tilt/shock sensors, 4G real-time upload.","image":"https://chinaheimayi.com/wp-content/uploads/2026/02/IoT-Data-Collection-Terminal-2.webp","tags":["GPS / BeiDou / LBS","4G real-time","Shock & tilt alert","7–10 day standby","IP65–IP68"]}
  ]},
  "cat-hvac": { "theme": "dark", "products": [
    {"code":"HVC","name":"Fan Coil Control Valve","desc":"Wireless FCU valve for zone-level HVAC control. Mounts directly on existing pipework with zero pipe cutting.","image":"https://chinaheimayi.com/wp-content/uploads/2026/02/Fan-Coil-Control-Valve-3.webp","tags":["DN15–DN25","AC220V / DC24V","M-Bus / LoRa / 4G","Fail-safe open"]},
    {"code":"HTT Room","name":"Wireless Room Temperature Controller","desc":"Battery-powered IoT thermostat. LoRaWAN / 4G. Mounts with 3M tape in 30 seconds. No wiring required.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/Temperature-Controller.webp","tags":["±0.3°C accuracy","5–7 yr battery","LoRaWAN / 4G"]},
    {"code":"HHU","name":"Ultrasonic Heat Energy Meter","desc":"Class 2 ultrasonic BTU meter. No moving parts. Verifies every kWh saved with hardware-grade accuracy.","image":"https://chinaheimayi.com/wp-content/uploads/2026/02/Ultrasonic-Heat-Meter-1.webp","tags":["Class 2","DN15–DN300","M-Bus / RS485 / NB-IoT / 4G","IP65–IP68"]},
    {"code":"PICV","name":"Pressure Independent Flow Control Valve","desc":"3-in-1: flow meter + temperature sensor + control valve. Automatic hydraulic balancing. 25%+ whole-system energy savings.","image":"https://chinaheimayi.com/wp-content/uploads/2025/10/V9-IoT-Smart-Balancing-Valve-1.png","tags":["DN15–DN50","100% valve authority","Ratio 100:1","RS485 / NB-IoT / LoRa"]},
    {"code":"PICV-L","name":"Large Caliber PICV Energy Valve","desc":"Large-diameter smart energy valve integrating ultrasonic flow measurement, temperature sensing and remote valve control.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/V8-Ultrasonic-Energy-Valve-Building-Use.webp","tags":["DN50–DN250","Class 2","4G / RS485","IP68"]},
    {"code":"HVA IoT","name":"Unit IoT Intelligent Valve","desc":"Smart IoT balance valve for centralized chilled water networks. Real-time return-temperature balancing across all building units.","image":"https://chinaheimayi.com/wp-content/uploads/2026/02/Balancing-Valve-5.webp","tags":["DN40–DN400","M-Bus / NB-IoT / 4G / LoRa","IP65–IP68","38,000 mAh battery"]},
    {"code":"T6","name":"Intelligent Temperature Control Switch","desc":"Wall-mount electronic thermostat with temperature sensing and smart cut-off. Controls heaters, chillers and HVAC units by setpoint.","image":"https://chinaheimayi.com/wp-content/uploads/2025/12/Intelligent-Temperature-Control-Switch-1.webp","tags":["5°C–35°C range","±1°C accuracy","AC 220V–240V","LoRa / 4G option"]}
  ]}
};
